package com.enviro365.etalente.seed;

import java.time.LocalDate;
import java.util.List;

import com.enviro365.etalente.jobs.domain.EmploymentType;
import com.enviro365.etalente.jobs.domain.Job;

/**
 * Hardcoded mock job listings used by the in-memory repository. Kept in its
 * own class so swapping the data source (e.g. a JSON file or a real DB) is a
 * single-point change.
 */
public final class MockJobData {

    private MockJobData() {
    }

    public static List<Job> jobs() {
        return List.of(
                Job.builder()
                        .id("job-1")
                        .title("Senior Software Engineer (Full Stack)")
                        .company("eTalente Systems")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("5+ Years")
                        .minYearsExperience(5)
                        .salaryRange("R85k - R120k")
                        .postedBy("Recruitment Team")
                        .closingDate(LocalDate.of(2026, 5, 24))
                        .description("""
                                Build and maintain the core talent platform.
                                Flutter on the client, Spring Boot on the server,
                                Postgres and event-driven integrations in between.""")
                        .skills(List.of("Java", "Spring Boot", "Flutter", "PostgreSQL", "AWS"))
                        .build(),
                Job.builder()
                        .id("job-2")
                        .title("Flutter Mobile Engineer")
                        .company("Kunye Labs")
                        .location("Remote, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R55k - R80k")
                        .postedBy("Talent Acquisition")
                        .closingDate(LocalDate.of(2026, 6, 10))
                        .description("Own the iOS and Android experience for the eTalente app.")
                        .skills(List.of("Flutter", "Dart", "Riverpod", "REST"))
                        .build(),
                Job.builder()
                        .id("job-3")
                        .title("Backend Engineer (Java)")
                        .company("Indaba Digital")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("4+ Years")
                        .minYearsExperience(4)
                        .salaryRange("R70k - R95k")
                        .postedBy("Recruitment Team")
                        .closingDate(LocalDate.of(2026, 5, 30))
                        .description("Ship resilient REST APIs on Spring Boot 3 and Java 21.")
                        .skills(List.of("Java", "Spring Boot", "Kafka", "PostgreSQL"))
                        .build(),
                Job.builder()
                        .id("job-4")
                        .title("DevOps Engineer")
                        .company("Fynbos Cloud")
                        .location("Centurion, ZA")
                        .type(EmploymentType.CONTRACT)
                        .experience("5+ Years")
                        .minYearsExperience(5)
                        .salaryRange("R700 - R900 / hr")
                        .postedBy("Platform Team")
                        .closingDate(LocalDate.of(2026, 5, 18))
                        .description("Harden our CI/CD and Kubernetes footprint.")
                        .skills(List.of("Kubernetes", "Terraform", "GitHub Actions", "AWS"))
                        .build(),
                Job.builder()
                        .id("job-5")
                        .title("Product Designer")
                        .company("eTalente Systems")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("2+ Years")
                        .minYearsExperience(2)
                        .salaryRange("R45k - R65k")
                        .postedBy("Design Guild")
                        .closingDate(LocalDate.of(2026, 6, 5))
                        .description("Design the end-to-end recruiter and candidate flows.")
                        .skills(List.of("Figma", "User Research", "Design Systems"))
                        .build(),
                Job.builder()
                        .id("job-6")
                        .title("Data Engineer")
                        .company("Karoo Analytics")
                        .location("Remote, ZA")
                        .type(EmploymentType.CONTRACT)
                        .experience("4+ Years")
                        .minYearsExperience(4)
                        .salaryRange("R650 - R850 / hr")
                        .postedBy("Analytics Team")
                        .closingDate(LocalDate.of(2026, 5, 28))
                        .description("Build the talent analytics warehouse on dbt and Snowflake.")
                        .skills(List.of("SQL", "dbt", "Snowflake", "Airflow"))
                        .build(),
                Job.builder()
                        .id("job-7")
                        .title("QA Automation Engineer")
                        .company("Baobab Software")
                        .location("Pretoria, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R40k - R60k")
                        .postedBy("Quality Guild")
                        .closingDate(LocalDate.of(2026, 6, 15))
                        .description("Extend our Playwright and JUnit coverage across the stack.")
                        .skills(List.of("Playwright", "JUnit", "CI/CD"))
                        .build(),
                Job.builder()
                        .id("job-8")
                        .title("Technical Recruiter")
                        .company("eTalente Systems")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("2+ Years")
                        .minYearsExperience(2)
                        .salaryRange("R35k - R55k")
                        .postedBy("People Operations")
                        .closingDate(LocalDate.of(2026, 6, 20))
                        .description("Own the engineering hiring pipeline end-to-end.")
                        .skills(List.of("Sourcing", "Interviewing", "ATS"))
                        .build(),
                Job.builder()
                        .id("job-9")
                        .title("Junior Frontend Developer")
                        .company("Protea Studios")
                        .location("Durban, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("1+ Years")
                        .minYearsExperience(1)
                        .salaryRange("R25k - R40k")
                        .postedBy("Recruitment Team")
                        .closingDate(LocalDate.of(2026, 7, 1))
                        .description("Level up on React and Flutter web while pairing with seniors.")
                        .skills(List.of("React", "TypeScript", "CSS"))
                        .build(),
                Job.builder()
                        .id("job-10")
                        .title("Engineering Manager")
                        .company("Indaba Digital")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("7+ Years")
                        .minYearsExperience(7)
                        .salaryRange("R110k - R150k")
                        .postedBy("Leadership")
                        .closingDate(LocalDate.of(2026, 5, 22))
                        .description("Lead two delivery squads and own the platform roadmap.")
                        .skills(List.of("Leadership", "Architecture", "Coaching"))
                        .build(),
                Job.builder()
                        .id("job-11")
                        .title("Security Engineer")
                        .company("Simba Security")
                        .location("Remote, ZA")
                        .type(EmploymentType.CONTRACT)
                        .experience("5+ Years")
                        .minYearsExperience(5)
                        .salaryRange("R750 - R950 / hr")
                        .postedBy("Security Guild")
                        .closingDate(LocalDate.of(2026, 6, 8))
                        .description("Threat-model and harden the talent platform end-to-end.")
                        .skills(List.of("AppSec", "OWASP", "Cloud Security"))
                        .build(),
                Job.builder()
                        .id("job-12")
                        .title("Frontend Developer Intern")
                        .company("eTalente Systems")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.INTERNSHIP)
                        .experience("0+ Years")
                        .minYearsExperience(0)
                        .salaryRange("R15k - R20k")
                        .postedBy("People Operations")
                        .closingDate(LocalDate.of(2026, 7, 12))
                        .description("12-month internship with a clear path to a permanent role.")
                        .skills(List.of("HTML", "CSS", "JavaScript"))
                        .build(),
                Job.builder()
                        .id("job-13")
                        .title("Product Designer")
                        .company("Amandla Works")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R55k - R80k")
                        .postedBy("Design Studio")
                        .closingDate(LocalDate.of(2026, 5, 30))
                        .description("Lead end-to-end product design for the employer dashboard.")
                        .skills(List.of("Figma", "Design Systems", "Prototyping"))
                        .build(),
                Job.builder()
                        .id("job-14")
                        .title("QA Automation Engineer")
                        .company("Kunye Labs")
                        .location("Remote, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R45k - R70k")
                        .postedBy("Quality Guild")
                        .closingDate(LocalDate.of(2026, 6, 12))
                        .description("Build and maintain the regression suite across web and mobile.")
                        .skills(List.of("Playwright", "Java", "CI/CD"))
                        .build(),
                Job.builder()
                        .id("job-15")
                        .title("Technical Writer")
                        .company("Karoo Analytics")
                        .location("Remote, ZA")
                        .type(EmploymentType.PART_TIME)
                        .experience("2+ Years")
                        .minYearsExperience(2)
                        .salaryRange("R28k - R42k")
                        .postedBy("Developer Experience")
                        .closingDate(LocalDate.of(2026, 5, 28))
                        .description("Own the public API docs and onboarding guides.")
                        .skills(List.of("Markdown", "OpenAPI", "Technical Writing"))
                        .build(),
                Job.builder()
                        .id("job-16")
                        .title("Site Reliability Engineer")
                        .company("Fynbos Cloud")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("4+ Years")
                        .minYearsExperience(4)
                        .salaryRange("R75k - R110k")
                        .postedBy("Platform Team")
                        .closingDate(LocalDate.of(2026, 6, 20))
                        .description("Keep the platform observable, on-call rotation included.")
                        .skills(List.of("Kubernetes", "Prometheus", "Terraform"))
                        .build(),
                Job.builder()
                        .id("job-17")
                        .title("Android Engineer")
                        .company("Kunye Labs")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("4+ Years")
                        .minYearsExperience(4)
                        .salaryRange("R70k - R100k")
                        .postedBy("Mobile Guild")
                        .closingDate(LocalDate.of(2026, 6, 15))
                        .description("Ship and maintain the native Android companion app.")
                        .skills(List.of("Kotlin", "Jetpack Compose", "Coroutines"))
                        .build(),
                Job.builder()
                        .id("job-18")
                        .title("iOS Engineer")
                        .company("Kunye Labs")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("4+ Years")
                        .minYearsExperience(4)
                        .salaryRange("R70k - R100k")
                        .postedBy("Mobile Guild")
                        .closingDate(LocalDate.of(2026, 6, 15))
                        .description("Ship and maintain the native iOS companion app.")
                        .skills(List.of("Swift", "SwiftUI", "Combine"))
                        .build(),
                Job.builder()
                        .id("job-19")
                        .title("Customer Success Manager")
                        .company("eTalente Systems")
                        .location("Remote, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("2+ Years")
                        .minYearsExperience(2)
                        .salaryRange("R40k - R60k")
                        .postedBy("Customer Success")
                        .closingDate(LocalDate.of(2026, 5, 31))
                        .description("Own onboarding and retention for SMB employer accounts.")
                        .skills(List.of("SaaS", "Account Management", "Onboarding"))
                        .build(),
                Job.builder()
                        .id("job-20")
                        .title("Business Analyst")
                        .company("Indaba Digital")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.CONTRACT)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R550 - R750 / hr")
                        .postedBy("Operations")
                        .closingDate(LocalDate.of(2026, 6, 5))
                        .description("Shape requirements for the upcoming billing module.")
                        .skills(List.of("Requirements", "SQL", "Stakeholder Management"))
                        .build(),
                Job.builder()
                        .id("job-21")
                        .title("Data Analyst")
                        .company("Karoo Analytics")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("2+ Years")
                        .minYearsExperience(2)
                        .salaryRange("R40k - R60k")
                        .postedBy("Data Guild")
                        .closingDate(LocalDate.of(2026, 6, 18))
                        .description("Build dashboards that answer hiring-funnel questions.")
                        .skills(List.of("SQL", "Looker", "Python"))
                        .build(),
                Job.builder()
                        .id("job-22")
                        .title("Machine Learning Engineer")
                        .company("Nguni AI")
                        .location("Remote, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("5+ Years")
                        .minYearsExperience(5)
                        .salaryRange("R90k - R130k")
                        .postedBy("AI Platform")
                        .closingDate(LocalDate.of(2026, 6, 28))
                        .description("Own the candidate-ranking model end-to-end.")
                        .skills(List.of("Python", "PyTorch", "MLOps"))
                        .build(),
                Job.builder()
                        .id("job-23")
                        .title("Recruitment Consultant")
                        .company("Talentium Africa")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R38k - R55k + comm.")
                        .postedBy("Talent Services")
                        .closingDate(LocalDate.of(2026, 5, 26))
                        .description("Source and place candidates into enterprise accounts.")
                        .skills(List.of("Sourcing", "LinkedIn Recruiter", "Negotiation"))
                        .build(),
                Job.builder()
                        .id("job-24")
                        .title("Marketing Content Writer")
                        .company("Amandla Works")
                        .location("Remote, ZA")
                        .type(EmploymentType.PART_TIME)
                        .experience("1+ Years")
                        .minYearsExperience(1)
                        .salaryRange("R20k - R32k")
                        .postedBy("Marketing")
                        .closingDate(LocalDate.of(2026, 5, 22))
                        .description("Craft blog posts, case studies and landing-page copy.")
                        .skills(List.of("Copywriting", "SEO", "Content Strategy"))
                        .build(),
                Job.builder()
                        .id("job-25")
                        .title("Graphic Design Intern")
                        .company("Amandla Works")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.INTERNSHIP)
                        .experience("0+ Years")
                        .minYearsExperience(0)
                        .salaryRange("R12k - R18k")
                        .postedBy("Brand Studio")
                        .closingDate(LocalDate.of(2026, 7, 18))
                        .description("Six-month internship supporting the brand team.")
                        .skills(List.of("Illustrator", "Photoshop", "Branding"))
                        .build(),
                Job.builder()
                        .id("job-26")
                        .title("Engineering Manager")
                        .company("eTalente Systems")
                        .location("Cape Town, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("7+ Years")
                        .minYearsExperience(7)
                        .salaryRange("R120k - R170k")
                        .postedBy("Engineering Leadership")
                        .closingDate(LocalDate.of(2026, 6, 30))
                        .description("Lead a cross-functional squad owning the talent search stack.")
                        .skills(List.of("Leadership", "Agile", "Hiring"))
                        .build(),
                Job.builder()
                        .id("job-27")
                        .title("Accountant")
                        .company("Veld Finance")
                        .location("Johannesburg, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("3+ Years")
                        .minYearsExperience(3)
                        .salaryRange("R45k - R65k")
                        .postedBy("Finance")
                        .closingDate(LocalDate.of(2026, 5, 29))
                        .description("Own the monthly close for the SA entity.")
                        .skills(List.of("IFRS", "Xero", "Reconciliations"))
                        .build(),
                Job.builder()
                        .id("job-28")
                        .title("Junior Backend Developer")
                        .company("Protea Studios")
                        .location("Remote, ZA")
                        .type(EmploymentType.FULL_TIME)
                        .experience("1+ Years")
                        .minYearsExperience(1)
                        .salaryRange("R28k - R42k")
                        .postedBy("Platform Team")
                        .closingDate(LocalDate.of(2026, 6, 2))
                        .description("Pair with seniors on the job-posting microservice.")
                        .skills(List.of("Java", "Spring Boot", "PostgreSQL"))
                        .build());
    }
}
